language: node_js

sudo: true

node_js:
  - "6"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - gulp

script: npm test

branches:
  only:
    - gh-pages
